[project]
name = "agents-intensive-capstone-project-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.18.0",
    "pdfplumber>=0.11.8",
    "python-docx>=1.2.0",
]
